In [1]:
import pandas as pd
import json 

def json_to_dataframe(json_file):
    """
    Reads a JSON file containing tweet data and converts it into a DataFrame.

    Parameters:
    json_file (str): Path to the JSON file.

    Returns:
    pd.DataFrame: DataFrame containing the tweet data.
    """
    with open(json_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Normalize JSON into a DataFrame
    df = pd.json_normalize(data)
    return df

In [5]:
input_file_path = "Arlukowicz_2023-10-16_2024-10-15_tweets.json"

In [6]:
df = json_to_dataframe(input_file_path)

In [7]:
df

,id,possibly_sensitive,conversation_id,edit_history_tweet_ids,created_at,lang,text,author_id,reply_settings,category,...,public_metrics.like_count,public_metrics.quote_count,public_metrics.bookmark_count,public_metrics.impression_count,referenced_tweets,in_reply_to_user_id,entities.mentions,entities.hashtags,context_annotations,entities.annotations
0,1846103375156277250,False,1846103375156277250,[1846103375156277250],2024-10-15T08:18:38.000Z,pl,15 października. To był nasz wspólny dzień! Pr...,101561338,everyone,Original,...,1202,14,7,19459,NaN,NaN,NaN,NaN,NaN,NaN
1,1846069735084921321,False,1846066439872041438,[1846069735084921321],2024-10-15T06:04:57.000Z,pl,@nat_dziedzic @RadioRebeliant Pozdrawiam i dzi...,101561338,everyone,Reply,...,7,0,0,165,"[{'type': 'replied_to', 'id': '184606769186331...",890595110685114369,"[{'start': 0, 'end': 13, 'username': 'nat_dzie...",NaN,NaN,NaN
2,1845868192758960129,False,1845868192758960129,[1845868192758960129],2024-10-14T16:44:06.000Z,pl,O polityce migracyjnej i rocznicy Koalicji jut...,101561338,everyone,Original,...,67,1,0,5624,NaN,NaN,NaN,"[{'start': 73, 'end': 81, 'tag': 'SuperFm'}]",NaN,NaN
3,1844821048773988690,False,1844821048773988690,[1844821048773988690],2024-10-11T19:23:07.000Z,pl,"Pan Prezydent w Sądzie Najwyższym. Warto. Tak,...",101561338,everyone,Original,...,459,2,1,13190,NaN,NaN,NaN,NaN,NaN,NaN
4,1843983476850385241,False,1843983476850385241,[1843983476850385241],2024-10-09T11:54:55.000Z,en,First meeting with future Commissioner for Fis...,101561338,everyone,Original,...,22,0,0,1614,NaN,NaN,"[{'start': 54, 'end': 66, 'username': 'CostasK...",NaN,"[{'domain': {'id': '46', 'name': 'Business Tax...","[{'start': 202, 'end': 216, 'probability': 0.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,1813659448428404856,False,1813659448428404856,[1813659448428404856],2024-07-17T19:38:03.000Z,pl,Poseł Romanowski. W 2024 w Radzie Europy odbył...,101561338,everyone,Original,...,566,1,7,15407,NaN,NaN,NaN,NaN,NaN,NaN
65,1813657783570726931,False,1813657783570726931,[1813657783570726931],2024-07-17T19:31:26.000Z,pl,Poseł Romanowski. Nie jest członkiem Zgromadze...,101561338,everyone,Original,...,857,5,6,18854,NaN,NaN,NaN,NaN,NaN,NaN
66,1813229013583778009,False,1813229013583778009,[1813229013583778009],2024-07-16T15:07:39.000Z,pl,Ale że tak z Niemcami z AFD? Nasi “bogobojni i...,101561338,everyone,Quote,...,778,1,2,15580,"[{'type': 'quoted', 'id': '1813137455656100306'}]",NaN,NaN,NaN,"[{'domain': {'id': '10', 'name': 'Person', 'de...",NaN
67,1813222571770319130,False,1813222571770319130,[1813222571770319130],2024-07-16T14:42:03.000Z,pl,A więc ruszamy do pracy! Ten Parlament Europej...,101561338,everyone,Original,...,350,4,0,13727,NaN,NaN,"[{'start': 152, 'end': 164, 'username': 'Europ...",NaN,"[{'domain': {'id': '88', 'name': 'Political Bo...",NaN
68,1813184241624093057,False,1813184241624093057,[1813184241624093057],2024-07-16T12:09:45.000Z,ca,Roberta! @EP_President @RobertaMetsola \nCongr...,101561338,everyone,Original,...,238,2,1,5699,NaN,NaN,"[{'start': 9, 'end': 22, 'username': 'EP_Presi...",NaN,"[{'domain': {'id': '88', 'name': 'Political Bo...",NaN